version: '3.8'
services:
  expo-builder:
    build: .
    volumes:
      - ./:/workspace
      - ${HOME}/.cache/expo-data:/root/.expo # persist expo auth creds
    working_dir: /workspace
    environment:
      - PROFILE=development # development|production
    stdin_open: true
    tty: true